CREATE DATABASE DbArmazem;

USE DbArmazem;

CREATE TABLE Categoria(
	ID INT PRIMARY KEY IDENTITY,
	nome VARCHAR(255) 
);

CREATE TABLE Prestador(
	ID INT PRIMARY KEY IDENTITY,
	nome VARCHAR(255)
);


CREATE TABLE TipoTransacao(
	ID INT PRIMARY KEY IDENTITY,
	nome VARCHAR(255)  
);

CREATE TABLE Armazem(
	ID INT PRIMARY KEY IDENTITY,
	nome VARCHAR(255) 
);

CREATE TABLE Item(
	ID INT PRIMARY KEY IDENTITY,
	nome VARCHAR(255),
	quantidadeMinima BIGINT ,
	numeroLoteRequerido BIT DEFAULT(0),
	FornecedorID INT FOREIGN KEY REFERENCES Prestador(ID) ,
	CategoriaID INT FOREIGN KEY REFERENCES Categoria(ID) ,
	LocalID INT FOREIGN KEY REFERENCES Armazem(ID)
	);


CREATE TABLE Pedido(
	ID INT PRIMARY KEY IDENTITY,
	dataPedido DATETIME2 ,
	dataEntrega DATETIME2 ,
	transportadoraID INT FOREIGN KEY REFERENCES Prestador(ID) ,
	lojaID INT FOREIGN KEY REFERENCES Armazem(ID),
	armazemOrigemID INT FOREIGN KEY REFERENCES Armazem(ID) ,
	armazemDestinoID INT FOREIGN KEY REFERENCES Armazem(ID) ,
	tipoTransacaoID INT FOREIGN KEY REFERENCES TipoTransacao(ID)
);

CREATE TABLE ItemPedido(
	ID INT PRIMARY KEY IDENTITY,
	numeroLote VARCHAR(255) ,
	Quantidade BIGINT ,
	pedidoID INT FOREIGN KEY REFERENCES Pedido(ID),
	itemID INT FOREIGN KEY REFERENCES Item(ID)
);

